### ISSUE TITLE
On some OSX installs build fails with undefined gmp symbols

### ISSUE THREAD

**Issue by dagit** [GaloisInc/blt#1]
On my machine, I can fix this by editing libblt/Makefile to add `LIBS += -lgmp`. This doesn't appear to be necessary on all OSX machines some some investigation is warranted. Might also want to make this a user tuneable feature of the makefile.

**Comment by benjaminfjones** [comment]
How have you installed `NTL` and `GLPK` on the machine that exhibits this behavior? Did you homebrew install them? Compile them from source? Other?

Also, can you tell me what C/C++ compiler you are using?

**Comment by benjaminfjones** [comment]
OK, I can reproduce the problem. I think, in general, that specifying the transitive dependency `-lgmp` at link time is the right answer. Alternatively, we could depend on `libtool` to figure it out automatically, but I don't want to depend on any more than we already do. See, e.g., [this question](http://stackoverflow.com/questions/11055569/linking-with-dynamic-library-with-dependencies).

**Comment by benjaminfjones** [comment]
Scratch that. The problem, I suspect, is that the dependencies (NTL, GLPK) you have installed are compiled against GMP, but the BLT build system doesn't know that. BLT doesn't depend on GMP, directly or indirectly, itself.

So the best solution seems to be that the user should specify additional libraries to link against in the `LDFLAGS` variable before calling `make`. See the top of the `Makefile`.

**Comment by benjaminfjones** [comment]
Updated the `Makefile` with some comments. Hopefully they are helpful.

https://github.com/GaloisInc/blt/commit/b917b89d37d76b165fb39b53c0a121b8410edf98
